# Generated by Django 6.0.3 on 2026-06-16 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlog',
            name='ip_address',
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('import', 'Import'), ('export', 'Export'), ('login', 'Login'), ('wipe', 'Wipe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='adminlog',
            table='admin_log',
        ),
    ]
