# Generated by Django 5.2.9 on 2026-03-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise', models.CharField(blank=True, max_length=50, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('key', models.IntegerField(blank=True, null=True)),
                ('id_2g', models.CharField(blank=True, max_length=50, null=True)),
                ('id_3g', models.CharField(blank=True, max_length=100, null=True)),
                ('id_4g', models.CharField(blank=True, max_length=100, null=True)),
                ('technology', models.CharField(blank=True, max_length=50, null=True)),
                ('business_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('commercial_district', models.CharField(blank=True, max_length=100, null=True)),
                ('cl_status', models.CharField(blank=True, max_length=100, null=True)),
                ('usf_status', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('pta_district', models.CharField(blank=True, max_length=100, null=True)),
                ('site_status', models.CharField(blank=True, max_length=50, null=True)),
                ('site_type', models.CharField(blank=True, max_length=50, null=True)),
                ('feb_26', models.CharField(blank=True, max_length=50, null=True)),
                ('arm', models.CharField(blank=True, max_length=200, null=True)),
                ('fca', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bvs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('act_90d', models.IntegerField(blank=True, null=True)),
                ('act_30d', models.IntegerField(blank=True, null=True)),
                ('act_90d_4g', models.IntegerField(blank=True, null=True)),
                ('hvc_base', models.IntegerField(blank=True, null=True)),
                ('tot_revn_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bvs_retailer', models.IntegerField(blank=True, null=True)),
                ('evc_retailer', models.IntegerField(blank=True, null=True)),
                ('minutes_outgoing', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('minutes_incoming', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('volume_gbs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('data_ntwrk_vol_4g', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fca_adjusted', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tot_revival', models.IntegerField(blank=True, null=True)),
                ('gross_churn', models.IntegerField(blank=True, null=True)),
                ('net_add', models.IntegerField(blank=True, null=True)),
                ('avg_dly_act', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('act_recharger', models.IntegerField(blank=True, null=True)),
                ('m0_revn', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mnp_fca', models.IntegerField(blank=True, null=True)),
                ('handset_4g', models.IntegerField(blank=True, null=True)),
                ('rchrg_face_value_mtd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pp_rechar_face_val_mtd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prepaid_dgtl_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('postpaid_dgtl_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('conventional_recharge', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_recharge', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('digi_recharge', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'site_data',
            },
        ),
    ]
