# Generated by Django 5.2.9 on 2026-03-20 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('designation', models.CharField(blank=True, choices=[('network_engineer', 'Network Engineer'), ('regional_manager', 'Regional Manager'), ('franchise_manager', 'Franchise Manager'), ('data_analyst', 'Data Analyst'), ('field_officer', 'Field Officer'), ('technical_lead', 'Technical Lead'), ('operations_manager', 'Operations Manager'), ('other', 'Other')], default='', max_length=50)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('region', models.CharField(blank=True, default='Central B', max_length=100)),
                ('employee_id', models.CharField(blank=True, default='', max_length=50)),
                ('bio', models.TextField(blank=True, default='', max_length=300)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
