# Generated by Django 6.0.3 on 2026-03-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("network_engineer", "Network Engineer"),
                    ("regional_manager", "Regional Manager"),
                    ("franchise_manager", "Franchise Manager"),
                    ("data_analyst", "Data Analyst"),
                    ("field_officer", "Field Officer"),
                    ("technical_lead", "Technical Lead"),
                    ("operations_manager", "Operations Manager"),
                    ("Executive", "Executive"),
                    ("other", "Other"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
