# Generated by Django 6.0.3 on 2026-03-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0003_alter_userprofile_designation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RD", "RD"),
                    ("ARM", "ARM"),
                    ("Manager", "Manager"),
                    ("Executive", "Executive"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
