# Generated by Django 6.0.3 on 2026-04-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0004_alter_userprofile_designation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitedata",
            old_name="feb_26",
            new_name="bisp_type",
        ),
        migrations.AddField(
            model_name="sitedata",
            name="region_main",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sitedata",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
