# Generated by Django 6.0.3 on 2026-04-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0005_rename_feb_26_sitedata_bisp_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitedata",
            name="key",
            field=models.CharField(blank=True, null=True),
        ),
    ]
