# Generated by Django 6.0.3 on 2026-04-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0006_alter_sitedata_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitedata",
            name="avg_dly_act",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
