# Generated by Django 6.0.3 on 2026-04-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0007_alter_sitedata_avg_dly_act"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="category",
            field=models.CharField(
                choices=[("Region", "Region"), ("BU", "BU"), ("ARM", "ARM")],
                default="Region",
                help_text="Region = full access | BU = locked to one business unit | ARM = locked to one ARM",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_arm",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Exact arm value from SiteData (used when category=ARM)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_business_unit",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Exact business_unit value from SiteData (used when category=BU)",
                max_length=100,
            ),
        ),
    ]
