# Generated by Django 6.0.3 on 2026-04-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_userprofile_last_seen_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitedata',
            name='bisp_type',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='digi_recharge',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='region_main',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='total_recharge',
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='avg_dly_act',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
