# Generated by Django 6.0.3 on 2026-04-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_remove_sitedata_bisp_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['year'], name='idx_year'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['month'], name='idx_month'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['key'], name='idx_key'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['region'], name='idx_region'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['business_unit'], name='idx_business_unit'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['commercial_district'], name='idx_commercial_district'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['franchise'], name='idx_franchise'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['technology'], name='idx_technology'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['site_status'], name='idx_site_status'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['arm'], name='idx_arm'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['latitude', 'longitude'], name='idx_lat_lng'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['year', 'month'], name='idx_year_month'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['year', 'month', 'region'], name='idx_year_month_region'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['year', 'month', 'business_unit'], name='idx_year_month_bu'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['year', 'month', 'commercial_district'], name='idx_year_month_district'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['year', 'month', 'franchise'], name='idx_year_month_franchise'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['year', 'month', 'key'], name='idx_year_month_key'),
        ),
    ]
