# Generated by Django 6.0.3 on 2026-05-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_alter_chatmessage_options_chatmessage_audio_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sitedata',
            name='idx_year',
        ),
        migrations.RemoveIndex(
            model_name='sitedata',
            name='idx_month',
        ),
        migrations.RemoveIndex(
            model_name='sitedata',
            name='idx_key',
        ),
        migrations.RemoveIndex(
            model_name='sitedata',
            name='idx_region',
        ),
        migrations.RemoveIndex(
            model_name='sitedata',
            name='idx_business_unit',
        ),
        migrations.RemoveIndex(
            model_name='sitedata',
            name='idx_commercial_district',
        ),
        migrations.RemoveIndex(
            model_name='sitedata',
            name='idx_franchise',
        ),
        migrations.RemoveIndex(
            model_name='sitedata',
            name='idx_technology',
        ),
        migrations.RemoveIndex(
            model_name='sitedata',
            name='idx_site_status',
        ),
        migrations.RemoveIndex(
            model_name='sitedata',
            name='idx_arm',
        ),
        migrations.RemoveIndex(
            model_name='sitedata',
            name='idx_lat_lng',
        ),
        migrations.RemoveIndex(
            model_name='sitedata',
            name='idx_year_month_region',
        ),
        migrations.RemoveIndex(
            model_name='sitedata',
            name='idx_year_month_bu',
        ),
        migrations.RemoveIndex(
            model_name='sitedata',
            name='idx_year_month_district',
        ),
        migrations.RemoveIndex(
            model_name='sitedata',
            name='idx_year_month_franchise',
        ),
        migrations.RemoveIndex(
            model_name='sitedata',
            name='idx_year_month_key',
        ),
        migrations.RenameIndex(
            model_name='sitedata',
            new_name='site_data_year_ce283d_idx',
            old_name='idx_year_month',
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='arm',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='business_unit',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='commercial_district',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='franchise',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='month',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='site_status',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='technology',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['business_unit', 'year', 'month'], name='site_data_busines_1da467_idx'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['arm', 'year', 'month'], name='site_data_arm_5f0274_idx'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['region', 'year', 'month'], name='site_data_region_48797f_idx'),
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='act_90d_4g',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='act_recharger',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='avg_dly_act',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='bvs_retailer',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='conventional_recharge',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='data_ntwrk_vol_4g',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='evc_retailer',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='fca_adjusted',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='gross_churn',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='handset_4g',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='hvc_base',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='m0_revn',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='minutes_incoming',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='minutes_outgoing',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='mnp_fca',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='net_add',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='postpaid_dgtl_amount',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='pp_rechar_face_val_mtd',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='prepaid_dgtl_amount',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='rchrg_face_value_mtd',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='tot_revival',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='volume_gbs',
        ),
    ]
