# Generated by Django 6.0.3 on 2026-05-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0013_remove_sitedata_idx_year_remove_sitedata_idx_month_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sitedata',
            name='site_data_busines_1da467_idx',
        ),
        migrations.RemoveIndex(
            model_name='sitedata',
            name='site_data_arm_5f0274_idx',
        ),
        migrations.RemoveIndex(
            model_name='sitedata',
            name='site_data_region_48797f_idx',
        ),
        migrations.RenameIndex(
            model_name='sitedata',
            new_name='idx_year_month',
            old_name='site_data_year_ce283d_idx',
        ),
        migrations.AddField(
            model_name='sitedata',
            name='act_90d_4g',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='act_recharger',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='avg_dly_act',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='bvs_retailer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='conventional_recharge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='data_ntwrk_vol_4g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='evc_retailer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='fca_adjusted',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='gross_churn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='handset_4g',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='hvc_base',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='m0_revn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='minutes_incoming',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='minutes_outgoing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='mnp_fca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='net_add',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='postpaid_dgtl_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='pp_rechar_face_val_mtd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='prepaid_dgtl_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='rchrg_face_value_mtd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='tot_revival',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='volume_gbs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='arm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='business_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='commercial_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='franchise',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='site_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='technology',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['year'], name='idx_year'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['month'], name='idx_month'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['key'], name='idx_key'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['region'], name='idx_region'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['business_unit'], name='idx_business_unit'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['commercial_district'], name='idx_commercial_district'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['franchise'], name='idx_franchise'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['technology'], name='idx_technology'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['site_status'], name='idx_site_status'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['arm'], name='idx_arm'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['latitude', 'longitude'], name='idx_lat_lng'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['year', 'month', 'region'], name='idx_year_month_region'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['year', 'month', 'business_unit'], name='idx_year_month_bu'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['year', 'month', 'commercial_district'], name='idx_year_month_district'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['year', 'month', 'franchise'], name='idx_year_month_franchise'),
        ),
        migrations.AddIndex(
            model_name='sitedata',
            index=models.Index(fields=['year', 'month', 'key'], name='idx_year_month_key'),
        ),
    ]
