# Generated by Django 6.0.3 on 2026-06-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0014_remove_sitedata_site_data_busines_1da467_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedata',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
