# Generated by Django 6.0.3 on 2026-06-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0017_alter_userprofile_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, choices=[('VP', 'VP')], default='', max_length=50),
        ),
    ]
