# Generated by Django 6.0.3 on 2026-05-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeldaily',
            name='arm',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='channeldaily',
            index=models.Index(fields=['region', 'business_unit', 'arm'], name='channel_cha_region_22ec57_idx'),
        ),
    ]
