# Generated by Django 6.0.3 on 2026-06-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_channeldaily_arm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channeldaily',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='channeldaily',
            name='channel_cha_region_c6a7b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='channeldaily',
            name='channel_cha_franchi_162afe_idx',
        ),
        migrations.RemoveIndex(
            model_name='channeldaily',
            name='channel_cha_date_0f8ef8_idx',
        ),
        migrations.RemoveIndex(
            model_name='channeldaily',
            name='channel_cha_region_22ec57_idx',
        ),
        migrations.AlterUniqueTogether(
            name='channeldaily',
            unique_together=set(),
        ),
    ]
