# Generated by Django 6.0.3 on 2026-06-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_channeldaily_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channeldaily',
            options={'ordering': ['-date']},
        ),
        migrations.AddIndex(
            model_name='channeldaily',
            index=models.Index(fields=['region', 'business_unit', 'date'], name='channel_dai_region_a475f1_idx'),
        ),
        migrations.AddIndex(
            model_name='channeldaily',
            index=models.Index(fields=['region', 'business_unit', 'arm'], name='channel_dai_region_80e24a_idx'),
        ),
        migrations.AddIndex(
            model_name='channeldaily',
            index=models.Index(fields=['franchise_id', 'date'], name='channel_dai_franchi_d736de_idx'),
        ),
        migrations.AddIndex(
            model_name='channeldaily',
            index=models.Index(fields=['date', 'region'], name='channel_dai_date_3da91f_idx'),
        ),
        migrations.AddIndex(
            model_name='channeldaily',
            index=models.Index(fields=['date'], name='channel_dai_date_4825cc_idx'),
        ),
        migrations.AddIndex(
            model_name='channeldaily',
            index=models.Index(fields=['arm', 'date'], name='channel_dai_arm_abad5e_idx'),
        ),
        migrations.AddIndex(
            model_name='channeldaily',
            index=models.Index(fields=['business_unit', 'date'], name='channel_dai_busines_8ed351_idx'),
        ),
        migrations.AddIndex(
            model_name='channeldaily',
            index=models.Index(fields=['date', 'business_unit', 'arm'], name='channel_dai_date_86f1d7_idx'),
        ),
        migrations.AlterModelTable(
            name='channeldaily',
            table='channel_daily',
        ),
    ]
