# Generated by Django 6.0.3 on 2026-06-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_alter_channeldaily_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeldaily',
            name='active_so_daily_avg',
            field=models.FloatField(default=0),
        ),
    ]
